# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('celular', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=8)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('direccion', models.CharField(max_length=80)),
                ('fecIngreso', models.DateField(blank=True)),
                ('reservas', models.BooleanField(default=False)),
                ('prestamos', models.BooleanField(default=False)),
            ],
        ),
    ]
