# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20170514_1903'),
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPrestamo', models.DateTimeField(auto_now_add=True)),
                ('fechaDevolucion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Prestamos',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva', models.CharField(max_length=6, unique=True)),
                ('fechaReserva', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='prestamos',
            field=models.BooleanField(default=False, help_text='Puede realizar prestamos'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='reservas',
            field=models.BooleanField(default=False, help_text='Puede realizar reservas'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.Estudiante'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Libro'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.Estudiante'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Libro'),
        ),
    ]
