# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_auto_20170514_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='reserva',
        ),
    ]
