# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_remove_reserva_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechaDevolucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaPrestamo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fechaReserva',
            field=models.DateField(),
        ),
    ]
