# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_auto_20170514_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecIngreso',
            field=models.DateField(blank=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaPrestamo',
            field=models.DateField(verbose_name='Fecha prestamo'),
        ),
    ]
