# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('isbn', models.CharField(max_length=13)),
                ('precio', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=14)),
                ('detalle', models.TextField()),
                ('autor', models.ManyToManyField(blank=True, to='biblioteca.Autor')),
            ],
        ),
    ]
