# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20170514_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
