# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_auto_20170520_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Categoria de libro',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Ubicacion de libro',
            },
        ),
        migrations.AlterField(
            model_name='libro',
            name='tipomaterial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.TipoMaterial', verbose_name='Tipo de material'),
        ),
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Categorias', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='libro',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Ubicacion', verbose_name='Ubicacion'),
        ),
    ]
